-- Create herbs table
create table if not exists public.herbs (
    id bigint generated by default as identity primary key,
    name text not null,
    scientific_name text not null,
    description text not null,
    benefits text[] default '{}',
    category text not null,
    preparation_methods text[] default '{}',
    image_url text,
    is_premium boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create indexes for better query performance
create index if not exists herbs_name_idx on public.herbs (name);
create index if not exists herbs_category_idx on public.herbs (category);
create index if not exists herbs_is_premium_idx on public.herbs (is_premium);

-- Set up row level security (RLS)
alter table public.herbs enable row level security;

-- Create policies
create policy "Allow public read access"
    on public.herbs
    for select
    to public
    using (true);

-- Only authenticated users can insert/update/delete
create policy "Allow authenticated users to modify herbs"
    on public.herbs
    for all
    to authenticated
    using (true)
    with check (true);
